const EngQuestions = [
	{
		number: 1,
		question: 'What is the capital city of France?',
		options: ['London', 'Paris', 'Berlin', 'Madrid'],
		answer: 'Paris',
	},
	{
		number: 2,
		question: 'What is the largest country in the world by area?',
		options: ['Russia', 'China', 'USA', 'Canada'],
		answer: 'Russia',
	},
	{
		number: 3,
		question: 'Which planet in our solar system is the largest?',
		options: ['Venus', 'Jupiter', 'Mars', 'Saturn'],
		answer: 'Jupiter',
	},
	{
		number: 4,
		question: 'What is the highest mountain in the world?',
		options: ['K2', 'Makalu', 'Everest', 'Lhotse'],
		answer: 'Everest',
	},
	{
		number: 5,
		question: 'Which country is known as the Land of the Rising Sun?',
		options: ['China', 'Japan', 'South Korea', 'North Korea'],
		answer: 'Japan',
	},
	{
		number: 6,
		question: 'What is the capital of Australia?',
		options: ['Melbourne', 'Sydney', 'Canberra', 'Brisbane'],
		answer: 'Canberra',
	},
	{
		number: 7,
		question: 'Which country is known as the Pearl of Africa?',
		options: ['Kenya', 'Tanzania', 'Uganda', 'Rwanda'],
		answer: 'Uganda',
	},
	{
		number: 8,
		question:
			'Which country gifted the Statue of Liberty to the United States?',
		options: ['France', 'Spain', 'Italy', 'Germany'],
		answer: 'France',
	},
	{
		number: 9,
		question: 'What is the largest ocean in the world?',
		options: [
			'Atlantic Ocean',
			'Indian Ocean',
			'Arctic Ocean',
			'Pacific Ocean',
		],
		answer: 'Pacific Ocean',
	},
	{
		number: 10,
		question: 'Which river is the longest in the world?',
		options: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'],
		answer: 'Nile',
	},
	{
		number: 11,
		question: 'Which language is spoken in Brazil?',
		options: ['Portuguese', 'Spanish', 'English', 'French'],
		answer: 'Portuguese',
	},
	{
		number: 12,
		question: 'What is the currency of Japan?',
		options: ['Yen', 'Dollar', 'Euro', 'Pound'],
		answer: 'Yen',
	},
	{
		number: 13,
		question: 'What is the capital of Spain',
		options: ['Barcelona', 'Madrid', 'Seville', 'Valencia'],
		answer: 'Madrid',
	},
	{
		number: 14,
		question:
			'Which country is the largest producer of coffee in the world?',
		options: ['Colombia', 'Brazil', 'Vietnam', 'Indonesia'],
		answer: 'Brazil',
	},
	{
		number: 15,
		question: 'What is the smallest country in the world by area?',
		options: ['Monaco', 'San Marino', 'Vatican City', 'Nauru'],
		answer: 'Vatican City',
	},
	{
		number: 16,
		question: 'What is the highest waterfall in the world?',
		options: [
			'Victoria Falls',
			'Niagara Falls',
			'Angel Falls',
			'Iguazu Falls',
		],
		answer: 'Angel Falls',
	},
	{
		number: 17,
		question: 'What is the capital of South Africa?',
		options: ['Cape Town', 'Johannesburg', 'Pretoria', 'Durban'],
		answer: 'Pretoria',
	},
	{
		number: 18,
		question:
			'Which country is home to the famous Angkor Wat temple complex?',
		options: ['Thailand', 'Cambodia', 'Myanmar', 'Vietnam'],
		answer: 'Cambodia',
	},
	{
		number: 19,
		question: 'Which country is known as the Land of Smiles?',
		options: ['Thailand', 'Indonesia', 'Philippines', 'Malaysia'],
		answer: 'Thailand',
	},
	{
		number: 20,
		question: 'Which country is known as the Emerald Isle?',
		options: ['Ireland', 'Scotland', 'England', 'Wales'],
		answer: 'Ireland',
	},
	{
		number: 21,
		question: 'What is the capital of Turkey?',
		options: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'],
		answer: 'Ankara',
	},
	{
		number: 22,
		question: 'What is the currency of Canada?',
		options: ['Dollar', 'Euro', 'Yen', 'Pound'],
		answer: 'Dollar',
	},
	{
		number: 23,
		question: 'What is the largest desert in the world?',
		options: [
			'Gobi Desert',
			'Sahara Desert',
			'Mojave Desert',
			'Arabian Desert',
		],
		answer: 'Sahara Desert',
	},
	{
		number: 24,
		question: 'What is the national animal of Australia?',
		options: ['Kangaroo', 'Koala', 'Emu', 'Wombat'],
		answer: 'Kangaroo',
	},
	{
		number: 25,
		question: 'What is the capital of Mexico?',
		options: ['Tijuana', 'Mexico City', 'Cancún', 'Acapulco'],
		answer: 'Mexico City',
	},
	{
		number: 26,
		question: 'What is the largest river in Africa?',
		options: ['Nile', 'Congo', 'Zambezi', 'Niger'],
		answer: 'Nile',
	},
	{
		number: 27,
		question: 'What is the capital of Spain?',
		options: ['Barcelona', 'Madrid', 'Valencia', 'Seville'],
		answer: 'Madrid',
	},
	{
		number: 28,
		question: 'Which country is known as the Land of the Rising Sun?',
		options: ['China', 'Korea', 'Japan', 'Taiwan'],
		answer: 'Japan',
	},
	{
		number: 29,
		question: 'What is the largest ocean in the world?',
		options: [
			'Atlantic Ocean',
			'Indian Ocean',
			'Arctic Ocean',
			'Pacific Ocean',
		],
		answer: 'Pacific Ocean',
	},
	{
		number: 30,
		question: 'What is the capital of Brazil?',
		options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Belo Horizonte'],
		answer: 'Brasília',
	},
	{
		number: 31,
		question: 'What is the currency of Japan?',
		options: ['Yuan', 'Won', 'Yen', 'Dollar'],
		answer: 'Yen',
	},
	{
		number: 32,
		question: 'What is the largest lake in the world by volume?',
		options: [
			'Lake Superior',
			'Lake Baikal',
			'Lake Victoria',
			'Caspian Sea',
		],
		answer: 'Lake Baikal',
	},
	{
		number: 33,
		question: 'Which country is the largest by population?',
		options: ['China', 'India', 'USA', 'Russia'],
		answer: 'China',
	},
	{
		number: 34,
		question: 'What is the capital of Italy?',
		options: ['Milan', 'Rome', 'Naples', 'Florence'],
		answer: 'Rome',
	},
	{
		number: 35,
		question: 'What is the highest mountain in the world?',
		options: ['K2', 'Mount Kilimanjaro', 'Mount Everest', 'Mount Fuji'],
		answer: 'Mount Everest',
	},
	{
		number: 36,
		question: 'What is the capital of South Korea?',
		options: ['Busan', 'Seoul', 'Incheon', 'Daegu'],
		answer: 'Seoul',
	},
	{
		number: 37,
		question: 'Which country is known as the Land of Fire and Ice?',
		options: ['Greenland', 'Iceland', 'Norway', 'Finland'],
		answer: 'Iceland',
	},
	{
		number: 38,
		question: 'What is the atomic number of carbon?',
		options: ['2', '6', '10', '14'],
		answer: '6',
	},
	{
		number: 39,
		question: 'What is the molecular formula of water?',
		options: ['H2O', 'CO2', 'NH3', 'CH4'],
		answer: 'H2O',
	},
	{
		number: 40,
		question:
			'What type of bond exists between two atoms that share electrons unequally?',
		options: ['Ionic', 'Covalent', 'Polar Covalent', 'Metallic'],
		answer: 'Polar Covalent',
	},
	{
		number: 41,
		question: 'Which element has the symbol Fe?',
		options: ['Iron', 'Gold', 'Silver', 'Copper'],
		answer: 'Iron',
	},
	{
		number: 42,
		question: 'Which of the following is a noble gas?',
		options: ['Oxygen', 'Nitrogen', 'Helium', 'Carbon Dioxide'],
		answer: 'Helium',
	},
	{
		number: 43,
		question: 'Which of the following is a strong acid?',
		options: ['HClO4', 'HNO3', 'H2SO3', 'H3PO4'],
		answer: 'HClO4',
	},
	{
		number: 44,
		question: 'Which of the following is NOT a state of matter?',
		options: ['Gas', 'Liquid', 'Solid', 'Plasma'],
		answer: 'Plasma',
	},
	{
		number: 45,
		question: 'What is the formula for sodium chloride?',
		options: ['NaClO4', 'Na2CO3', 'NaHCO3', 'NaCl'],
		answer: 'NaCl',
	},
	{
		number: 46,
		question: 'Which of the following is a reducing agent?',
		options: [
			'Oxidizing agent',
			'Proton acceptor',
			'Proton donor',
			'Electron donor',
		],
		answer: 'Electron donor',
	},
	{
		number: 47,
		question: 'What is the SI unit of pressure?',
		options: ['Pascal', 'Newton', 'Joule', 'Watt'],
		answer: 'Pascal',
	},
	{
		number: 48,
		question:
			'What type of reaction occurs when two or more substances combine to form a single substance?',
		options: ['Decomposition', 'Combustion', 'Synthesis', 'Neutralization'],
		answer: 'Synthesis',
	},
	{
		number: 49,
		question:
			'What is the process called when a solid changes directly into a gas?',
		options: ['Evaporation', 'Sublimation', 'Condensation', 'Deposition'],
		answer: 'Sublimation',
	},
	{
		number: 50,
		question: 'What is the pH of a neutral solution?',
		options: ['0', '7', '14', '1'],
		answer: '7',
	},
	{
		number: 51,
		question: 'What is the chemical formula for methane?',
		options: ['CH4', 'CO2', 'NH3', 'H2O'],
		answer: 'CH4',
	},
	{
		number: 52,
		question: 'What is the atomic symbol for gold?',
		options: ['Ag', 'Au', 'Fe', 'Cu'],
		answer: 'Au',
	},
	{
		number: 53,
		question:
			'What is the name of the process in which a liquid changes into a gas at its boiling point?',
		options: ['Condensation', 'Evaporation', 'Sublimation', 'Deposition'],
		answer: 'Evaporation',
	},
	{
		number: 54,
		question: 'What is the chemical formula for sulfuric acid?',
		options: ['HCl', 'HNO3', 'H2SO4', 'H3PO4'],
		answer: 'H2SO4',
	},
	{
		number: 55,
		question: 'What is the name of the element with the symbol Mg?',
		options: ['Magnesium', 'Manganese', 'Mercury', 'Molybdenum'],
		answer: 'Magnesium',
	},
	{
		number: 56,
		question:
			'What is the name of the process in which a gas changes directly into a solid?',
		options: ['Deposition', 'Sublimation', 'Condensation', 'Evaporation'],
		answer: 'Deposition',
	},
	{
		number: 57,
		question: 'What is the chemical formula for ammonia?',
		options: ['NH4+', 'NO3-', 'NH3', 'N2H4'],
		answer: 'NH3',
	},
];
