const EngQuestions = [
	{
		number: 1,
		question: 'What is the capital city of France?',
		options: ['London', 'Paris', 'Berlin', 'Madrid'],
		answer: 'Paris',
	},
	{
		number: 2,
		question: 'What is the largest country in the world by area?',
		options: ['Russia', 'China', 'USA', 'Canada'],
		answer: 'Russia',
	},
	{
		number: 3,
		question: 'Which planet in our solar system is the largest?',
		options: ['Venus', 'Jupiter', 'Mars', 'Saturn'],
		answer: 'Jupiter',
	},
	{
		number: 4,
		question: 'What is the highest mountain in the world?',
		options: ['K2', 'Makalu', 'Everest', 'Lhotse'],
		answer: 'Everest',
	},
	{
		number: 5,
		question: 'Which country is known as the Land of the Rising Sun?',
		options: ['China', 'Japan', 'South Korea', 'North Korea'],
		answer: 'Japan',
	},
	{
		number: 6,
		question: 'What is the capital of Australia?',
		options: ['Melbourne', 'Sydney', 'Canberra', 'Brisbane'],
		answer: 'Canberra',
	},
	{
		number: 7,
		question: 'Which country is known as the Pearl of Africa?',
		options: ['Kenya', 'Tanzania', 'Uganda', 'Rwanda'],
		answer: 'Uganda',
	},
	{
		number: 8,
		question:
			'Which country gifted the Statue of Liberty to the United States?',
		options: ['France', 'Spain', 'Italy', 'Germany'],
		answer: 'France',
	},
	{
		number: 9,
		question: 'What is the largest ocean in the world?',
		options: [
			'Atlantic Ocean',
			'Indian Ocean',
			'Arctic Ocean',
			'Pacific Ocean',
		],
		answer: 'Pacific Ocean',
	},
	{
		number: 10,
		question: 'Which river is the longest in the world?',
		options: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'],
		answer: 'Nile',
	},
	{
		number: 11,
		question: 'Which language is spoken in Brazil?',
		options: ['Portuguese', 'Spanish', 'English', 'French'],
		answer: 'Portuguese',
	},
	{
		number: 12,
		question: 'What is the currency of Japan?',
		options: ['Yen', 'Dollar', 'Euro', 'Pound'],
		answer: 'Yen',
	},
	{
		number: 13,
		question: 'What is the capital of Spain',
		options: ['Barcelona', 'Madrid', 'Seville', 'Valencia'],
		answer: 'Madrid',
	},
	{
		number: 14,
		question:
			'Which country is the largest producer of coffee in the world?',
		options: ['Colombia', 'Brazil', 'Vietnam', 'Indonesia'],
		answer: 'Brazil',
	},
	{
		number: 15,
		question: 'What is the smallest country in the world by area?',
		options: ['Monaco', 'San Marino', 'Vatican City', 'Nauru'],
		answer: 'Vatican City',
	},
	{
		number: 16,
		question: 'What is the highest waterfall in the world?',
		options: [
			'Victoria Falls',
			'Niagara Falls',
			'Angel Falls',
			'Iguazu Falls',
		],
		answer: 'Angel Falls',
	},
	{
		number: 17,
		question: 'What is the capital of South Africa?',
		options: ['Cape Town', 'Johannesburg', 'Pretoria', 'Durban'],
		answer: 'Pretoria',
	},
	{
		number: 18,
		question:
			'Which country is home to the famous Angkor Wat temple complex?',
		options: ['Thailand', 'Cambodia', 'Myanmar', 'Vietnam'],
		answer: 'Cambodia',
	},
	{
		number: 19,
		question: 'Which country is known as the Land of Smiles?',
		options: ['Thailand', 'Indonesia', 'Philippines', 'Malaysia'],
		answer: 'Thailand',
	},
	{
		number: 20,
		question: 'Which country is known as the Emerald Isle?',
		options: ['Ireland', 'Scotland', 'England', 'Wales'],
		answer: 'Ireland',
	},
	{
		number: 21,
		question: 'What is the capital of Turkey?',
		options: ['Ankara', 'Istanbul', 'Izmir', 'Antalya'],
		answer: 'Ankara',
	},
	{
		number: 22,
		question: 'What is the currency of Canada?',
		options: ['Dollar', 'Euro', 'Yen', 'Pound'],
		answer: 'Dollar',
	},
	{
		number: 23,
		question: 'What is the largest desert in the world?',
		options: [
			'Gobi Desert',
			'Sahara Desert',
			'Mojave Desert',
			'Arabian Desert',
		],
		answer: 'Sahara Desert',
	},
	{
		number: 24,
		question: 'What is the national animal of Australia?',
		options: ['Kangaroo', 'Koala', 'Emu', 'Wombat'],
		answer: 'Kangaroo',
	},
	{
		number: 25,
		question: 'What is the capital of Mexico?',
		options: ['Tijuana', 'Mexico City', 'Cancún', 'Acapulco'],
		answer: 'Mexico City',
	},
	{
		number: 26,
		question: 'What is the largest river in Africa?',
		options: ['Nile', 'Congo', 'Zambezi', 'Niger'],
		answer: 'Nile',
	},
	{
		number: 27,
		question: 'What is the capital of Spain?',
		options: ['Barcelona', 'Madrid', 'Valencia', 'Seville'],
		answer: 'Madrid',
	},
	{
		number: 28,
		question: 'Which country is known as the Land of the Rising Sun?',
		options: ['China', 'Korea', 'Japan', 'Taiwan'],
		answer: 'Japan',
	},
	{
		number: 29,
		question: 'What is the largest ocean in the world?',
		options: [
			'Atlantic Ocean',
			'Indian Ocean',
			'Arctic Ocean',
			'Pacific Ocean',
		],
		answer: 'Pacific Ocean',
	},
	{
		number: 30,
		question: 'What is the capital of Brazil?',
		options: ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Belo Horizonte'],
		answer: 'Brasília',
	},
	{
		number: 31,
		question: 'What is the currency of Japan?',
		options: ['Yuan', 'Won', 'Yen', 'Dollar'],
		answer: 'Yen',
	},
	{
		number: 32,
		question: 'What is the largest lake in the world by volume?',
		options: [
			'Lake Superior',
			'Lake Baikal',
			'Lake Victoria',
			'Caspian Sea',
		],
		answer: 'Lake Baikal',
	},
	{
		number: 33,
		question: 'Which country is the largest by population?',
		options: ['China', 'India', 'USA', 'Russia'],
		answer: 'China',
	},
	{
		number: 34,
		question: 'What is the capital of Italy?',
		options: ['Milan', 'Rome', 'Naples', 'Florence'],
		answer: 'Rome',
	},
	{
		number: 35,
		question: 'What is the highest mountain in the world?',
		options: ['K2', 'Mount Kilimanjaro', 'Mount Everest', 'Mount Fuji'],
		answer: 'Mount Everest',
	},
	{
		number: 36,
		question: 'What is the capital of South Korea?',
		options: ['Busan', 'Seoul', 'Incheon', 'Daegu'],
		answer: 'Seoul',
	},
	{
		number: 37,
		question: 'Which country is known as the Land of Fire and Ice?',
		options: ['Greenland', 'Iceland', 'Norway', 'Finland'],
		answer: 'Iceland',
	},
];
